.Dd June 02 2010
.Dt BATTRAY 1
.Os
.Sh NAME
.Nm Battray
.Nd Display an battery status notification tray icon
.Sh SYNOPSIS
.Nm battray
.Op Fl hv
.Op Fl p Ar platform
.Op Fl d Ar datadir
.Op Fl f Ar configfile
.Op Fl i Ar pol_interval
.Sh DESCRIPTION
.Nm
is a tray icon aka status icon to notify you of your battery status and do
some action depending on it.
.Pp
.Bl -tag -width Ds
.It Fl h , Fl -help
Display help message and exit.
.It Fl v , Fl -version
Display version and exit.
.It Fl p , Fl -platform
Use this platform file (Absolute path), normally this is autodetected.
.It Fl d , Fl -datadir
Datadir to get icons and platform file from.
.It Fl f , Fl -file
Configuration file to use. A configuration file is mandatory.
.It Fl i , Fl -interval
Poll the system every n seconds.
.El
.Sh CONFIGURATION
The configuration file is imported in Python, any valid Python code goes.
.Bl -tag -width Ds
.It Va datadir Vt (string)
Datadir to get icons and platform file from.
.It Va pollInterval Vt (int)
Poll the system every n seconds.
.It Va events
Several variables and functions are available, this allows us to undertake
certain events at certain times.
See the example
.Pa battrayrc.py
configuration file for more information.
.El
.Sh PLATFORM FILE
.Pp
Battray gets it's data from using a command-line utility provided by the
Operating System.
Almost every OS a slightly different utility and/or to fetch the battery
status, this is why we need a platform file to implement each platform.
.Pp
I looked at implementing a C module, while this is pretty generic, there are
plenty of #IFDEF's for specific platforms. There is also little or no speed
advantage over the current method and it would be significantly harder to
maintain.
.Pp
These files are imported (and reload()-ed when needed) by the main script. Any
valid Python syntax goes.
.Pp
List of variables accessed
Mandatory variables, these must be present:
.Bl -tag -width Ds
.It Va ac Vt (bool)
Connected to AC? None if unknown.
.It Va percent Vt (int)
Battery power remaining in percent. 255 if unknown.
.It Va lifetime Vt (int)
Battery time remaining in minutes. 255 if unknown.
.It Va charging Vt (bool)
Are we charging the battery? None if unknown.
.El
.Pp
Optional variables, these will just be ignored if not set:
.Bl -tag -width Ds
.It Va tooltip Vt (string)
Additional info in the tooltip.
.El
.Sh EXAMPLES
An example file
.Pa battrayrc.py
should be included in the package. 
.Sh BUGS
The configuration could be a bit easier, the fact that it's imported in Python
makes configuration pretty flexible, but also makes it more difficult for
non-python programmers.
.Pp
Multiple batteries are not supported.
.Sh SEE ALSO
.Xr python 1
.Xr apm 8
.Xr acpidump 8
.Xr apm 4
.Xr acpi 4
.Sh AUTHORS
.An Martin Tournoij Aq martin@arp242.net
.An Linux support by Andy Mikhaylenko Aq andy@neithere.net
.Pp
Feel free to use, modify, and redistribute battray as you see fit. There are
no restrictions.
