.TH "battray" 1 "Battray 1.3" "Martin Tournoij <martin@arp242.net>"
.SH NAME
.P
Battray \-\- Display an battery status notification tray icon
.SH SYNOPSIS
battray [-hv] [-p platform] [-d datadir] [-f configfile] [-i pol_interval]
.SH DESCRIPTION
.P
battray is a tray icon aka status icon to notify you of your battery status and do
some action depending on it.
.P
 \-h, \-\-help
     Display help message and exit.
 \-v, \-\-version
     Display version and exit.
 \-p, \-\-platform
     Use this platform file (Absolute path), normally this is autode\-
     tected.
 \-d, \-\-datadir
     Datadir to get icons and platform file from.
 \-f, \-\-file
     Configuration file to use. A configuration file is mandatory.
 \-i, \-\-interval
     Poll the system every n seconds.
.SH CONFIGURATION
.P
The configuration file is imported in Python, any valid Python code goes.
.P
 datadir (string)
     Datadir to get icons and platform file from. Usually not required.
.P
 pollInterval (int)
     Poll the system every n seconds.
.SH PLATFORM FILE
.P
Battray gets it's data from using a command\-line utility provided by the
Operating System.  Almost every OS a slightly different utility and/or to
fetch the battery status, this is why we need a platform file to imple\-
ment each platform.
.P
I looked at implementing a C module, while this is pretty generic, there
are plenty of #IFDEF's for specific platforms. There is also little or no
speed advantage over the current method and it would be significantly
harder to maintain.
.P
These files are imported (and reload()\-ed when needed) by the main
script. Any valid Python syntax goes.
.P
List of variables accessed Mandatory variables, these must be present:
.P
 ac (bool)
     Connected to AC? None if unknown.
 percent (int)
     Battery power remaining in percent. 255 if unknown.
 lifetime (int)
     Battery time remaining in minutes. 255 if unknown.
 charging (bool)
     Are we charging the battery? None if unknown.
.P
Optional variables, these will just be ignored if not set:
.P
 tooltip (string)
     Additional info in the tooltip.
.SH EXAMPLES
.P
An example file battrayrc_default.py is included in the package.
.SH BUGS
.RS
.IP \(bu 3
The configuration could be a bit easier, the fact that it’s imported in Python
makes configuration pretty flexible, but also makes it more difficult for
non\-python programmers.
.IP \(bu 3
Multiple batteries are not supported.
.RE
.SH SEE ALSO
.P
python(1) apm(8) acpidump(8) apm(4) acpi(4)
.SH AUTHORS
.P
Martin Tournoij <martin@arp242.net>
Linux support by Andy Mikhaylenko <andy@neithere.net>
.P
Feel free to use, modify, and redistribute battray as you see fit. There are no
restrictions.
.\" man code generated by txt2tags 2.6 (http://txt2tags.org)
.\" cmdline: txt2tags -o - --target man doc/battray.t2t
